### ISSUE TITLE
Add nav easter egg

### ISSUE THREAD

**Issue by tinystride** [sparkbox/sparkbox-website#42]
@zastrow and I talked about detecting shake events on devices that register it, using it to open / close the nav.

Here's a reference: http://stackoverflow.com/questions/4475219/detect-a-shake-in-ios-safari-with-javascript

I quickly tested on iOS Safari and Samsung Galaxy S3; works as expected.

**Comment by bryanbraun** [comment]
This wasn't ever added (yes, I spent the last 5 minutes shaking my phone to make sure, ha ha).

The ship has probably sailed, so I'll go ahead and close this issue, just like @emilykggray closed sparkbox/seesparkbox.com#13.
